name: 🐞 Bug 反馈
description: 如何提交一份有意义的 Bug 反馈
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### 先决条件
        - **[常见问题解决方案](https://scpcbgame.cn/help.html)有没有提到过解决方案？** 如果有，先尝试解决方案。如果方案无效，请在下文提及。
        - **这是 bug 还是特性？** 任何类似“*SCP-079 收容室大门打不开*”的 bug 反馈将会以“无效”关闭。
        - **这是汉化版的 bug 还是原版就存在的 bug？** 如果你反馈的 bug 在原版就存在，则有可能会被“放弃”关闭。

        已证实**完全没有可能**修复的 bug 将以“放弃”关闭。

        > Troubleshooting any problem without the error log is like driving with your eyes closed.<br>
        > 在没有错误日志的情况下对任何问题进行故障排除就像闭着眼睛开车一样。
        >
        > ——[Apache 官方文档 Getting Started 篇](https://www.docs4dev.com/docs/zh/apache/2.4/reference/getting-started.html)
  - type: checkboxes
    id: check
    attributes:
      label: 先决条件
      description: 以下是提交 Issue 的先决条件。
      options:
      - label: 常见问题解决方案 中未提及或方案无效。
        required: true
      - label: 这是 bug 而不是特性。
        required: true
      - label: 这是一个在原版就存在的 bug。
        required: false
  - type: textarea
    id: description
    attributes:
      label: 描述 Bug
      description: 描述一下这个 bug，包括何时、何地、出现前发生了什么。
    validations:
        required: true
  - type: textarea
    id: information
    attributes:
      label: 电脑信息
      description: 这是你的电脑相关信息，一般来说没有意义，但这有时对于排查有一定帮助，越详细越好。
      placeholder: |
        - 操作系统：
        - 处理器：
        - 内存：
        - 游戏路径：
    validations:
        required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 这里是有关于 bug 的截图。你可以将崩溃窗口和游戏界面一同截下，然后放在这里。
    validations:
        required: false