#define 常量表达式 constexpr
#define 十六位字符 char16_t
#define 三十二位字符 char32_t
#define 推断类型 decltype
#define 空指针 nullptr
#define 静态异常 noexcept
#define 静态断言 static_assert
#define 自动 auto
#define 汇编 _asm
#define 常量转换 const_cast
#define 动态转换 dynamic_cast
#define 运行时转换 reinterpret_cast
#define 静态转换 static_cast
#define 跳出 break
#define 继续 continue
#define 转至 goto
#define 分支 switch
#define 情况 case
#define 默认 default
#define 抓取 catch
#define 抛出 throw
#define 尝试 try
#define 字符 char
#define 宽字符 wchar_t
#define 常量 const
#define 结构 struct
#define 类 class
#define 联合 union
#define 删除 delete
#define 新建 new
#define 布尔值 bool
#define 真 true
#define 假 false
#define 如果 if
#define 否则 else
#define 返回 return
#define 无符号 unsigned
#define 整数 int
#define 单浮点 float
#define 双浮点 double
#define 长整数 long
#define 短整数 short
#define 有符号 signed
#define 枚举 enum
#define 如果 if
#define 否则 else
#define 返回 return
#define 无符号 unsigned
#define 整数 int
#define 单浮点 float
#define 双浮点 double
#define 长整数 long
#define 短整数 short
#define 有符号 signed
#define 枚举 enum
#define 导出 export
#define 外来的 extern
#define 友元 friend
#define 内联 inline
#define 命名空间 namespace
#define 运算符 operator
#define 私有 private
#define 保护 protected
#define 寄存 register
#define 静态 static
#define 大小 sizeof
#define 模板 template
#define 此 this
#define 类型定义 typedef
#define 虚 virtual
#define 类型名 typeid
#define 类型名 typename
#define 使用 using
#define 空 void
#define 入口 int main()